### ISSUE TITLE
undefined symbol: R__Bool_to_C__Bool

### ISSUE THREAD

**Issue by j-rahman** [tybenz/vimdeck#56]
I installed `vimdeck` on a Fedora 36 machine without any hiccups. After installation, I downloaded the `slides.md` example file found in this repository to test the installation. I ran `vimdeck slides.md` as instructed. However, the program crashed and produced the following error message.

```
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': ~/.local/share/gem/ruby/extensions/x86_64-linux/3.1.0/rmagick-2.15.4/RMagick2.so: undefined symbol: R__Bool_to_C__Bool - ~/.local/share/gem/ruby/extensions/x86_64-linux/3.1.0/rmagick-2.15.4/RMagick2.so (LoadError)
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from ~/.local/share/gem/ruby/gems/rmagick-2.15.4/lib/rmagick_internal.rb:12:in `<top (required)>'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from ~/.local/share/gem/ruby/gems/rmagick-2.15.4/deprecated/RMagick.rb:6:in `<top (required)>'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from ~/.local/share/gem/ruby/gems/rasciiart-0.0.9/lib/asciiart.rb:2:in `<top (required)>'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from ~/.local/share/gem/ruby/gems/vimdeck-0.3.3/lib/vimdeck.rb:3:in `<top (required)>'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from ~/.local/share/gem/ruby/gems/vimdeck-0.3.3/bin/vimdeck:26:in `<top (required)>'
        from ~/bin/vimdeck:25:in `load'
        from ~/bin/vimdeck:25:in `<main>'
```

**Comment by j-rahman** [comment]
I noticed that `asciiart` produces the exact same error. So, I suppose the problem has to do with `asciiart` in some manner.
